//
//  BUSandboxConfig.m
//  BuckleUp
//
//  Copyright 2011 Martin Planer
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

#import "BUSandboxConfig.h"

@implementation BUSandboxConfig

- (id)initWithVersion: (BUVersion*)version
{
    self = [super init];
    if (self) {
        configVersion = version;
        
        actions = [[NSMutableArray alloc] init];
    }
    
    return self;
}

- (void) addAction: (BUAction<BUConfigItemProtocol>*)action
{
    [actions addObject:action];
}

#pragma mark -
#pragma mark BUConfigItemProtocol Methods

- (NSString*) configString
{
    NSMutableString* config = [[NSMutableString alloc] init];
    
    // Write Header
    [config appendString:@"; Seatbelt config file generated by BuckleUp\n"];
    [config appendString:@"; URL: https://github.com/maruchinu/BuckleUp\n"];
    [config appendString:@"\n"];
    
    // Write Version
    [config appendFormat:@"%@\n", [configVersion configString]];
    
    // Write Actions
    for (NSObject<BUConfigItemProtocol>* configItem in actions) 
    {
        [config appendFormat:@"%@\n", [configItem configString]];
    }
    
    return [config autorelease];
}

#pragma mark -
#pragma mark Convenience Methods

+ (BUSandboxConfig *)configWithVersion:(BUVersion *)version
{
    return [[[self alloc] initWithVersion:version] autorelease];
}

@end
